name: Using Environment Variables and Secrets

on: workflow_dispatch

jobs:
  env_secrets_demo:
    name: Using Environment Variables and Secrets
    runs-on: ubuntu-latest
    env:
      STATIC_ENV_VAR: "This is a static environment variable"
    steps:
      - name: Print Environment Variable
        run: |
          echo "Static Env Var: $STATIC_ENV_VAR"

      - name: Access Secret (Stored in GitHub Secrets)
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "Accessing secret (not printed in logs for security)"
          echo "Secret length: " $(echo $MY_SECRET | wc -c) "characters"

      - name: Ensure Secrets Are Not Exposed
        run: |
          echo "Verifying that secrets are not leaked in logs"
          echo "Sanitized Secret: '$MY_SECRET' (not shown for security)"

      - name: Confirm Successful Execution
        run: |
          echo "Workflow executed successfully without exposing secrets."
