name: Cache Dependencies for Playwright Tests  # Workflow name displayed in GitHub Actions.

on: push  # Triggers the workflow on every push event.

jobs:
  cache-dependencies:  # Defines a job for running Playwright tests with caching.
    name: Run Playwright Tests with Cache  # The display name of the job.
    runs-on: ubuntu-latest  # Specifies the Ubuntu environment for execution.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin  # Uses the Eclipse Temurin JDK.
          java-version: 21  # Installs Java version 21.
          cache: maven  # Enables automatic caching for Maven dependencies.

      - name: Restore Maven dependencies cache  # Restores previously cached Maven dependencies.
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository  # Specifies the directory to cache (Maven's local repository).
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          # Generates a unique cache key based on OS and pom.xml hash.
          restore-keys: |
            ${{ runner.os }}-maven-  # Fallback key if an exact match isn't found.

      - name: Build & Install  # Builds the project, using cached dependencies if available.
        run: mvn -B install -D skipTests --no-transfer-progress

      - name: Install Playwright Browsers
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
        # Installs required browsers and dependencies for Playwright.

      - name: Run tests
        run: mvn test  # Executes Playwright test suite.
