name: Upload & Display Playwright Reports
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install Playwright dependencies
        run: npx playwright install --with-deps

      - name: Build and Test with Maven
        run: mvn clean test

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            target/playwright-report
            test-results

      - name: Display Test Report in GitHub UI
        run: echo "## Playwright Test Results" >> $GITHUB_STEP_SUMMARY
