name: Run Custom Playwright Action

on: push

jobs:
  custom-action:
    name: Run Custom Playwright Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Simulate Playwright test output
        run: |
          mkdir -p test-results
          echo "Sample Playwright test output" > test-results/report.txt

      - name: Run custom action to format summary
        uses: ./.github/actions/playwright-summary