name: Containerized Testing

on:
  push:
  pull_request:

jobs:
  test:
    name: Containerized Testing
    runs-on: ubuntu-latest
    container:
      image: maven:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Playwright with dependencies
        run: mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

      - name: Install dependencies
        run: mvn install

      - name: Run Playwright tests
        run: mvn test
