name: "Parallel Tests"

on: workflow_dispatch

jobs:
  build-and-test:
    name: "Parallel Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Install Playwright with dependencies
        run: mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

      - name: Install dependencies
        run: mvn install

      - name: Build and run tests
        run: mvn clean test -Dplaywright.browserName=${{ matrix.browser }}
