name: "Parallel Tests"

on: workflow_dispatch

jobs:
  build-and-test:
    name: "Parallel Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build and run tests
        run: mvn clean test -Dplaywright.browserName=${{ matrix.browser }}
